### PR TITLE
Bump package-lock to match marked version

### PR DESCRIPTION
**Pull request by efhjones**
I forgot to commit the package-lock.json in the [PR to bump a dependency](https://github.com/zapier/formatic/pull/94) a moment ago. So let's bump it 🙄

### CODE REVIEW

**Comment by efhjones** [comment]
@vitorbal thanks for approving the last PR! I screwed up and forgot to commit the package json 🙄 Would you mind reviewing this PR as well? Thanks!

**Comment by vitorbal** [comment]
@efhnones damn that packae-lock.json! :)

**Comment by efhjones** [comment]
Thanks a bunch for the speedy review @vitorbal ! (Also don't want to make you feel obligated, I won't be upset if you wait until your regular working hours to approve 😄 )

**Comment by vitorbal** [comment]
haha no worries, @efhjones! I was checking my phone for something else and noticed it was a pretty small PR :)

**Pull request merged**
